### ISSUE TITLE
Pasting ReferenceExecute into DecomposeProvider not working due to Log_Verbose not Found

### ISSUE THREAD

**Issue by GPadley** [HPCE/hpce-2018-cw5#2]
Upon pasting in there ReferenceExecution function into the decompose.hpp file in the provider folder, make all is unable to build the program giving this error. I am unable to see why Log_Verbose is not being passed through when it is included within the original decompose.hpp file.

![image](https://user-images.githubusercontent.com/17782581/52959275-badd9580-338d-11e9-8af2-c1641b4b6d28.png)

**Comment by jjd06** [comment]
This is because your "provided" version isn't in the `puzzler` namespace, whereas the reference version is. You can either:

- Put it in it (`namespace puzzler { ... };`),
- Grant access to everything in it (`using namespace puzzler;`) or
- Accept that you'll have to add a few `puzzler::`s in (here, `puzzler::Log_Verbose`).

Whether or not you do this at all, and (if you do) how, is up to you.
